# 报文恶意注册拦截配置
   
:hotels:
  :Lakewood:
    :rating: 3
    :regular:
      :weekday: 110
      :weekend: 90
    :rewards:
      :weekday: 80
      :weekend: 80
  :Bridgewood:
    :rating: 4
    :regular:
      :weekday: 160
      :weekend: 60
    :rewards:
      :weekday: 110
      :weekend: 50
  :Ridgewood:
    :rating: 5
    :regular:
      :weekday: 220
      :weekend: 150
    :rewards:
      :weekday: 100
      :weekend: 40
